### ISSUE TITLE
Создать счётчик введённых байтов

### ISSUE THREAD

**Issue by ghost** [alyonakova/IO-lab1-character-device#3]
Нужно создать счётчик байтов, введённых в символьное устройство при помощи операции `write`.

- [x] При загрузке модуля в ядро (`ch_drv_init`) счётчик обнуляется.

- [x] При попытке чтения из устройства (при вызове `my_read`) в кольцевой буфер выводится сообщение, содержащее значение счётчика, например *«Total amount of written data so far: 42 bytes»*.

- [x] При попытке записи в устройство (при вызове `my_write`) к счётчику добавляется длина вводимого диапазона байтов (аргумент `len`).

- [x] При выгрузке модуля из ядра (`ch_drv_exit`) последнее значение счётчика выводится в кольцевой буфер.

**Comment by ghost** [comment]
Счётчик, вероятно, можно оформить как статическую переменную типа `size_t`.

**Comment by alyonakova** [comment]
Сделано! :owl:
